package org.example.enums;

public enum UserStep {
    NEW,START,REGISTER_BUTTON ,NAME,SURNAME,PHONE, LOCATION , FINISHED , MENU , MY_LOCATION_BUTTON,
    CALL_EMERGENCY_BUTTON, EMERGENCY_BUTTON , POLICE_BUTTON , AMBULANCE_BUTTON, FIREMAN_BUTTON , BACK ,
    NO_SURE , SURE,
    PERSONAL_DATA,


     ADMIN_START,ADD_ADMIN_NAME, ADD_ADMIN_CHAT_ID

}
